name: Makefile CI

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: make install

      - name: Formatting
        run: make format

      - name: Linting
        run: make lint

      - name: Testing
        run: make test
